### ISSUE TITLE
stanice9$params

### ISSUE THREAD

**Issue by MarekLu** [manmatej/chmu-process#1]
Je správně tento řádek v kódu pro stahování?

`stanice9$params <- apply(stanice9[16:24], MARGIN = 1, function(x) sum(!is.na(x)))`

Po stažení všech metrik z CHMU má tabulka stanice9 „802 obs. of 34 variables“ a příkaz apply vrátí vektor s devíti položkami:

`14 14 14 14 14 14 14 14 32`

To pak nejde spojit dohromady – přidat do dalšího sloupce ke stanice9:

`Error in set(x, j = name, value = value) : 
  Supplied 9 items to be assigned to 802 items of column 'params'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.`

Použití rep() tady ale podle mě není řešení.

**Comment by manmatej** [comment]
Máte pravdu, děkuji. Je to opravené. Kód je správně, ale csv mělo sloupce navíc (nahrál jsem verzi, kde už slupce byly ačkoliv v průběhu kódu vznikají, tak tam byly dvakrát)

**Comment by MarekLu** [comment]
Nejsem si úplně jistý, jestli oprava pomohla. Výsledkem apply je stále vektor s devíti položkami, který nejde přidat jako sloupec params k tabulce stanice9, která má 802 řádků.

**Comment by manmatej** [comment]
Zkuste to teď.
Chyběla tam čárka.  stanice9[,16:24] 
Ale u mě to fungovalo i bez ní.

**Comment by MarekLu** [comment]
Děkuji, už to funguje.

Čárka má být asi i u tohoto. Co vlastně tento řádek dělá?

`which(apply(stanice9[,16:24], MARGIN = 1, function(x) sum(!is.na(x)))==0)`

Jinak jsem si všiml, že ve zdrojovém CSV se stanicemi jsou chybné souřadnice X u dvou stanic: Nová Bystřice a Praha-Chodov. Nedala se vytvořit tabulka stanice_sf.

Vyřešil jsem to zatím záplatou (dělám v data.table):

`stanice9[id == "P1PCHO01", X := "14.51197"]`
`stanice9[id == "C2NBYS01", X := "15.10315"]`
`stanice9[, X := as.numeric(X)]`

**Comment by manmatej** [comment]
děkuju. ty souřadnice rozbil excel. Jak jsem to otevřel v excelu, interpretoval to jako datum. Opravil jsem souřadnice. Ten řádek 
which(apply(stanice9[,16:24], MARGIN = 1, function(x) sum(!is.na(x)))==0) 

tam nepatří. To jsem jen zkoumal, pro které stanice nejsou ke stažení žádná data.

**Comment by MarekLu** [comment]
Ještě jsem když tak našel drobnosti v unzip_process.R:

1) Před operacemi se soubory je potřeba `setwd(unzips)`

2) V řádku years má být `skip = "Měsíc"` – dlouho jsem zkoumal ten podivný regex "M?s?c" :-)

3) Totéž je ještě ve smyčce v řádku datum

**Comment by manmatej** [comment]
díky za pomoc s vyčištěním. opraveno.
